language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  api_key:
    secure: CMopI5F7xZb9JO6NiecSMfKdQVt0u0Agsttfljni5UfEQ2ZCzM0sxU969x8g11B5sM/htJeY//RSyy7gSLYIl5Z4m3qsi/qNm4Wz+Q8dKS8l2R6Oq+iY0oM4uSPA0zfIJ7gpIxae9GplMuYroM9Aip+wfOKjw5TvNxiyVGsP7apgIz10Mwr5yaloQ9KQ4cH9tF9CPVAeTEeYyoD97GfjPq75gB0ZeAlyYXNjQ2suveEpGc9yf1lYolWvLXemXm7lu6EJHqq6KFuQ1DtJRQqLhocQPC4+BQ+f8ELMZPjPhlD5Zq8wLCK214QNanl+rnWbGsKDR+GJzoTpzMInq72gNywTf74KfwsBQKsKNenXeUbVodjmmsfC5MsLqrlu/F32iGGIIHBZUZZ7YOfCtyfxmCUECb0Odu5Gbhp9yXMYxPugWmG/jGHuQdUvMZ9ZisBnGXoX+H5vMUD09/1Oz3tXCyQy7uQGZGdXR400ZNlLwb1EckWyIxXj3SSe50mleYP7DmUntodpPt6OQOjZmxjX3ZpzsJcLur//B0WPokII5awJ565bhj9KvFs+eagKBpMLccyldniCAy6p0wkDJIKSBIfsRZ4uOnCRBHa0dYqPEpjD1Dj2XOv64kmP/OUPRz185CcM8qf+IB5qv21geCiIxZ4F4W2wcnMt9ibVZuszqVU=
